chore: remove unnecessary regions fetch
The regions store is populated elsewhere already so no need to do it again here.

Also, $organization may not be defined on mount which would lead to:

TypeError: Cannot read properties of undefined (reading '$id')